extract:
  monogo_to_minio:
    mongodb_uri: "mongodb://root:root@host.docker.internal:27017/"
    database_name: "healthcare_db"
    collection_name: "patients"
    minio_endpoint: "http://host.docker.internal:9000"
    minio_access_key: "NWLUIMTyWmDpvc7rDTYe"
    minio_secret_key: "KX6vXLk0dz42NkBRgsV5gRIpmVYlyOfpg6joowzS"
    minio_bucket_name: "bronze-data"
    minio_object_key: "patients.csv"

  postgres_to_minio:
    pg_conn_params:
      host: host.docker.internal
      port: '5432'
      database: petrol
      user: airflow
      password: airflow

    minio_endpoint: "http://host.docker.internal:9000"
    minio_access_key: "NWLUIMTyWmDpvc7rDTYe"
    minio_secret_key: "KX6vXLk0dz42NkBRgsV5gRIpmVYlyOfpg6joowzS"
    minio_bucket_name: "bronze-data"
    minio_object_key: "used_petrol_cars.csv"
    query: "SELECT * FROM car_data1"

transformation_params:
  minio_server_url: "http://host.docker.internal:9000"
  access_key: "NWLUIMTyWmDpvc7rDTYe"
  secret_key: "KX6vXLk0dz42NkBRgsV5gRIpmVYlyOfpg6joowzS"
  source_bucket: "bronze-data"
  destination_bucket: "silver-data"
  source_object_key: "ToyotaCorolla.csv"
  destination_object_key: "processed_data.csv"
  column_types_to_convert:
    Model: "string"
    Price: "double"
    Age_08_04: "int"
    Mfg_Month: "int"
    Mfg_Year: "int"
    KM: "int"
    Fuel_Type: "string"
    HP: "int"
    Met_Color: "string"
    Color: "string"
    Automatic: "string"
    cc: "int"
    Doors: "int"
    Gears: "int"
    Quarterly_Tax: "int"
    Weight: "int"
    Mfr_Guarantee: "string"
    BOVAG_Guarantee: "string"
    Guarantee_Period: "int"
    ABS: "string"
    Airbag_1: "string"
    Airbag_2: "string"
    Airco: "string"
    Automatic_airco: "string"
    Boardcomputer: "string"
    CD_Player: "string"
    Central_Lock: "string"
    Powered_Windows: "string"
    Power_Steering: "string"
    Radio: "string"
    Mistlamps: "string"
    Sport_Model: "string"
    Backseat_Divider: "string"
    Metallic_Rim: "string"
    Radio_cassette: "string"
    Tow_Bar: "string"
  columns_to_remove:
    - "Id"
  feature_engineering_transformations:
    Car_Age: "pd.Timestamp.now().year - Mfg_Year"
    Mileage: "KM / Car_Age"
  numerical_columns_list:
    - "Age_08_04"
    - "KM"
    - "HP"
    - "cc"
    - "Doors"
    - "Gears"
    - "Quarterly_Tax"
    - "Weight"
    - "Guarantee_Period"
    - "Mfg_Year"
    - "Price"
