minio_server_url: "http://host.docker.internal:9000"
access_key: "NWLUIMTyWmDpvc7rDTYe"
secret_key: "KX6vXLk0dz42NkBRgsV5gRIpmVYlyOfpg6joowzS"
source_bucket: "bronze-data"
destination_bucket: "inference-data"
source_object_key: "inference.csv"
destination_object_key: "processed_inference_data.csv"
column_types_to_convert:
    Model: "string"
    Age_08_04: "int"
    Mfg_Month: "int"
    Mfg_Year: "int"
    KM: "int"
    Fuel_Type: "string"
    HP: "int"
    Met_Color: "string"
    Color: "string"
    Automatic: "string"
    cc: "int"
    Doors: "int"
    Gears: "int"
    Quarterly_Tax: "int"
    Weight: "int"
    Mfr_Guarantee: "string"
    BOVAG_Guarantee: "string"
    Guarantee_Period: "int"
    ABS: "string"
    Airbag_1: "string"
    Airbag_2: "string"
    Airco: "string"
    Automatic_airco: "string"
    Boardcomputer: "string"
    CD_Player: "string"
    Central_Lock: "string"
    Powered_Windows: "string"
    Power_Steering: "string"
    Radio: "string"
    Mistlamps: "string"
    Sport_Model: "string"
    Backseat_Divider: "string"
    Metallic_Rim: "string"
    Radio_cassette: "string"
    Tow_Bar: "string"
numerical_columns_list:
    - "Age_08_04"
    - "KM"
    - "HP"
    - "cc"
    - "Doors"
    - "Gears"
    - "Quarterly_Tax"
    - "Weight"
    - "Guarantee_Period"
    - "Mfg_Year"
