minio_server_url: 'http://host.docker.internal:9000'
access_key: 'NWLUIMTyWmDpvc7rDTYe'
secret_key: 'KX6vXLk0dz42NkBRgsV5gRIpmVYlyOfpg6joowzS'
model_uri: 'runs:/1779880744a9437890fa61afac6c1fbb/model'
source_bucket: 'inference-data'
source_object_key: 'processed_inference_data.csv'
destination_bucket: 'gold-data'
destination_object_key: 'predictions.csv'
mlflow_tracking_uri: 'http://host.docker.internal:5000'